# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qgisdashboard
                                 A QGIS plugin
 QGIS Dashboard that enables users to create their own customized dashboards
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-15
        copyright            : (C) 2026 by Isaac Enage
        email                : isaacenagework@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load qgisdashboard class from file qgisdashboard.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_dashboard import qgisdashboard
    return qgisdashboard(iface)
